rest-client:
  orfeo:
    url: https://apigesdocrest.movilidadbogota.gov.co/Dev/creaRadicado

spring:
  # Spring Data JPA configuration
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  # Database
  datasource:
    jndi-name: java:/sircDS
    driver-class-name: oracle.jdbc.OracleDriver
    #url: jdbc:oracle:thin:@172.30.6.93:1521:FABRICA
    #username: sirc
    #password: SIRC
    #BaseSoft
    #url: jdbc:oracle:thin:@204.110.52.87:1521:orcl
    #username: SIRC
    #password: pLGSks4Y

security:
  jwt:
    secret: HYgAf)rr_6-ts9

feign:
  httpclient:
    disableSslValidation: true

parametro-simur: URL.PQR
