rest-client:
  orfeo:
    url: https://apigesdocrest.movilidadbogota.gov.co/Dev/creaRadicado

spring:
  # Spring Data JPA configuration
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  # Database
  datasource:
    jndi-name: java:/sircDS
    driver-class-name: oracle.jdbc.OracleDriver
    #url: jdbc:oracle:thin:@172.30.6.93:1521:FABRICA
    #username: sirc
    #password: SIRC
    #BaseSoft
    #url: jdbc:oracle:thin:@101.44.27.227:1521:orcl
    #username: SIRC
    #password: 4J%vh]i2OQ

security:
  jwt:
    secret: HYgAf)rr_6-ts9

feign:
  httpclient:
    disableSslValidation: true

pqr.url.consulta.radicado: URL.PQR
pqr.url.orfeo: URL.PQR.ORFEO
pqr.url.orfeo.usuario.radica: URL.PQR.ORFEO.USUARIO.RADICA
pqr.url.orfeo.departamento: URL.PQR.ORFEO.DEPARTAMENTO
####################
#Mensajes Negocio.##
####################
mensaje.calificacion.exito: "Calificación Guardada con Éxito"
mensaje.conductor.no.existe: "Conductor No Existe."
mensaje.calificacion.existe: "Ya realizó una calificación en las ultimas 12 horas a éste conductor."
mensaje.pqr.existe: "Ya realizó una PQR en en las ultimas 12 horas a éste conductor."
mensaje.pqr.calificacion.guardada: "Calificación Guardada y Radicado PQR con éxito, puedes visualizarlo en: "
mensaje.pqr.radicado.exito: "Radicado con éxito, puedes visualizarlo en: "
mensaje.pqr.radicado.fallido: "No radicado, falta número de identificación"
parametro.automatico: Si